apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-application
  namespace: argo
spec:
  arguments:
    parameters:
    - name: site_name
      value: "hanu-deploy-apps"
    - name: manifest_repo_url
      value: "https://github.com/openinfradev/decapod-manifests"
    - name: revision
      value: "main"
    - name: app_prefix
      value: ""
  templates:
  - name: createApp
    inputs:
      parameters:
      - name: app_group
      - name: path
      - name: target_cluster  # set to site_name by default
      - name: namespace
      # More sync options will be supported when they become necessary
      - name: sync_option
        enum:
        - no_option
        - replace
    activeDeadlineSeconds: 900
    container:
      name: 'create'
      image: docker.io/sktdev/argocd:latest
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -c
      - |
        # log into Argo CD server
        ./argocd login $ARGO_SERVER --plaintext --insecure --username $ARGO_USERNAME \
        --password $ARGO_PASSWORD

        TARGET_CLUSTER="{{workflow.parameters.site_name}}"
        if [[ -n "{{inputs.parameters.target_cluster}}" ]]; then
          TARGET_CLUSTER="{{inputs.parameters.target_cluster}}"
        fi

        # TODO: another option is to set default app_prefix to 'site_name' and always apply that prefix.
        ARGOCD_APP_NAME=$PATH
        ARGOCD_APP_LABEL=$APP_GROUP
        if [[ -n "{{workflow.parameters.app_prefix}}" ]]; then
          ARGOCD_APP_NAME="{{workflow.parameters.app_prefix}}-$PATH"
          ARGOCD_APP_LABEL="{{workflow.parameters.app_prefix}}-$APP_GROUP"
        fi

        # check if the argocd app already exists.
        ./argocd app get $ARGOCD_APP_NAME
        if [[ $? -ne 0 ]]; then
          # create new application if it doesn't exist.
          ./argocd app create $ARGOCD_APP_NAME --repo $REPO --revision $REVISION --path $SITE_NAME/$APP_GROUP/$PATH --dest-namespace $NAMESPACE --dest-name $TARGET_CLUSTER --project $APP_GROUP --label app=$ARGOCD_APP_LABEL --directory-recurse
        fi

        if [[ "$SYNC_OPTION" == "replace"]]; then
          ./argocd app set $ARGOCD_APP_NAME --sync-policy automated --auto-prune --sync-option Replace=true
        else
          ./argocd app set $ARGOCD_APP_NAME --sync-policy automated --auto-prune
        fi
        ./argocd app sync $ARGOCD_APP_NAME --async
        ./argocd app wait $ARGOCD_APP_NAME --health
      envFrom:
        - secretRef:
            name: "decapod-argocd-config"
      env:
        - name: SITE_NAME
          value: "{{workflow.parameters.site_name}}"
        - name: REPO
          value: "{{workflow.parameters.manifest_repo_url}}"
        - name: REVISION
          value: "{{workflow.parameters.revision}}"
        - name: APP_GROUP
          value: "{{inputs.parameters.app_group}}"
        - name: PATH
          value: "{{inputs.parameters.path}}"
        - name: NAMESPACE
          value: "{{inputs.parameters.namespace}}"
        - name: SYNC_OPTION
          value: "{{inputs.parameters.sync_option}}"

  - name: installApps
    inputs:
      parameters:
      - name: app_list
      - name: app_group
      - name: target_cluster
      - name: sync_option
    steps:
    - - name: "InstallApps"
        template: createApp
        arguments:
          parameters:
          - {name: app_group, value: "{{inputs.parameters.app_group}}"}
          - {name: path, value: "{{item.path}}"}
          - {name: namespace, value: "{{item.namespace}}"}
          - {name: target_cluster, value: "{{inputs.parameters.target_cluster}}"}
          - {name: sync_option, value: "{{inputs.parameters.sync_option}}"}
        withParam: "{{inputs.parameters.app_list}}"
